

INSERT  INTO TRACAO VALUES (TRACAO_SEQUENCE.NEXTVAL,'combust�o');
INSERT  INTO TRACAO VALUES (TRACAO_SEQUENCE.NEXTVAL,'el�trico');

INSERT  INTO CATEGORIA VALUES (CATEGORIA_SEQUENCE.NEXTVAL,'particular');
INSERT  INTO CATEGORIA VALUES (CATEGORIA_SEQUENCE.NEXTVAL,'aluguel');
INSERT  INTO CATEGORIA VALUES (CATEGORIA_SEQUENCE.NEXTVAL,'oficial');

INSERT  INTO MODELO VALUES (MODELO_SEQUENCE.NEXTVAL,'modelo01');
INSERT  INTO MODELO VALUES (MODELO_SEQUENCE.NEXTVAL,'modelo02');
INSERT  INTO MODELO VALUES (MODELO_SEQUENCE.NEXTVAL,'modelo03');

INSERT INTO PAIS VALUES (PAIS_SEQUENCE.NEXTVAL, 'pais01');
INSERT INTO PAIS VALUES (PAIS_SEQUENCE.NEXTVAL, 'pais02');
INSERT INTO PAIS VALUES (PAIS_SEQUENCE.NEXTVAL, 'pais03');

INSERT INTO FABRICANTE VALUES (FABRICANTE_SEQUENCE.NEXTVAL, 1, 'fabricante01');
INSERT INTO FABRICANTE VALUES (FABRICANTE_SEQUENCE.NEXTVAL, 2, 'fabricante02');
INSERT INTO FABRICANTE VALUES (FABRICANTE_SEQUENCE.NEXTVAL, 3, 'fabricante03');

INSERT INTO AUTOMOVEL VALUES (AUTOMOVEL_SEQUENCE.NEXTVAL,'AAA1111',1,1,1,1);
INSERT INTO AUTOMOVEL VALUES (AUTOMOVEL_SEQUENCE.NEXTVAL,'BBB2222',2,2,2,2);
INSERT INTO AUTOMOVEL VALUES (AUTOMOVEL_SEQUENCE.NEXTVAL,'CCC3333',3,1,3,3);

