DROP TABLE IF EXISTS MODELO;
DROP TABLE IF EXISTS TRACAO;
DROP TABLE IF EXISTS CATEGORIA;
DROP TABLE IF EXISTS PAIS;
DROP TABLE IF EXISTS FABRICANTE;
DROP TABLE IF EXISTS AUTOMOVEL;

DROP SEQUENCE IF EXISTS MODELO_SEQUENCE;
DROP SEQUENCE IF EXISTS CATEGORIA_SEQUENCE;
DROP SEQUENCE IF EXISTS TRACAO_SEQUENCE;
DROP SEQUENCE IF EXISTS PAIS_SEQUENCE;
DROP SEQUENCE IF EXISTS FABRICANTE_SEQUENCE;
DROP SEQUENCE IF EXISTS AUTOMOVEL_SEQUENCE;

DROP TRIGGER IF EXISTS MODELO_ON_INSERT;
DROP TRIGGER IF EXISTS TRACAO_ON_INSERT;
DROP TRIGGER IF EXISTS CATEGORIA_ON_INSERT;
DROP TRIGGER IF EXISTS PAIS_ON_INSERT;
DROP TRIGGER IF EXISTS FABRICANTE_ON_INSERT;
DROP TRIGGER IF EXISTS AUTOMOVEL_ON_INSERT;

CREATE SEQUENCE MODELO_SEQUENCE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE CATEGORIA_SEQUENCE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TRACAO_SEQUENCE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PAIS_SEQUENCE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FABRICANTE_SEQUENCE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE AUTOMOVEL_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE TABLE MODELO (
	ID NUMBER NOT NULL,
	DESCRICAO VARCHAR(50) NOT NULL
);

ALTER TABLE MODELO
	ADD (
		CONSTRAINT PK_MODELO PRIMARY KEY (ID)
  	);

CREATE TABLE CATEGORIA (
	ID NUMBER NOT NULL,
	DESCRICAO VARCHAR(50) NOT NULL
);

ALTER TABLE CATEGORIA
	ADD (
		CONSTRAINT PK_CATEGORIA PRIMARY KEY (ID)
  	);

CREATE TABLE TRACAO (
	ID NUMBER NOT NULL,
	DESCRICAO VARCHAR(50) NOT NULL
);

ALTER TABLE TRACAO
	ADD (
		CONSTRAINT PK_TRACAO PRIMARY KEY (ID)
  	);

CREATE TABLE PAIS (
	ID NUMBER NOT NULL,
	NOME VARCHAR(50) NOT NULL
);

ALTER TABLE PAIS
	ADD (
		CONSTRAINT PK_PAIS PRIMARY KEY (ID)
  	);

CREATE TABLE FABRICANTE (
	ID NUMBER NOT NULL,
	ID_PAIS NUMBER NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	CONSTRAINT FK_FABRICANTE_PAIS FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID)
);

ALTER TABLE FABRICANTE
	ADD (
		CONSTRAINT PK_FABRICANTE PRIMARY KEY (ID)
  	);

CREATE TABLE AUTOMOVEL (
	ID NUMBER NOT NULL,
	PLACA VARCHAR(7) NOT NULL,
	ID_MODELO NUMBER NOT NULL,
	ID_TRACAO NUMBER NOT NULL,
	ID_CATEGORIA NUMBER NOT NULL,
	ID_FABRICANTE NUMBER NOT NULL,
	CONSTRAINT FK_AUTOMOVEL_MODELO FOREIGN KEY (ID_MODELO) REFERENCES MODELO(ID),
	CONSTRAINT FK_AUTOMOVEL_TRACAO FOREIGN KEY (ID_TRACAO) REFERENCES TRACAO(ID),
	CONSTRAINT FK_AUTOMOVEL_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID),
	CONSTRAINT FK_AUTOMOVEL_FABRICANTE FOREIGN KEY (ID_FABRICANTE) REFERENCES FABRICANTE(ID)
);

ALTER TABLE AUTOMOVEL
	ADD (
		CONSTRAINT PK_AUTOMOVEL PRIMARY KEY (ID)
  	);

INSERT  INTO TRACAO VALUES (TRACAO_SEQUENCE.NEXTVAL,'combustão');
INSERT  INTO TRACAO VALUES (TRACAO_SEQUENCE.NEXTVAL,'elétrico');

INSERT  INTO CATEGORIA VALUES (CATEGORIA_SEQUENCE.NEXTVAL,'particular');
INSERT  INTO CATEGORIA VALUES (CATEGORIA_SEQUENCE.NEXTVAL,'aluguel');
INSERT  INTO CATEGORIA VALUES (CATEGORIA_SEQUENCE.NEXTVAL,'oficial');

INSERT  INTO MODELO VALUES (MODELO_SEQUENCE.NEXTVAL,'modelo01');
INSERT  INTO MODELO VALUES (MODELO_SEQUENCE.NEXTVAL,'modelo02');
INSERT  INTO MODELO VALUES (MODELO_SEQUENCE.NEXTVAL,'modelo03');

INSERT INTO PAIS VALUES (PAIS_SEQUENCE.NEXTVAL, 'pais01');
INSERT INTO PAIS VALUES (PAIS_SEQUENCE.NEXTVAL, 'pais02');
INSERT INTO PAIS VALUES (PAIS_SEQUENCE.NEXTVAL, 'pais03');

INSERT INTO FABRICANTE VALUES (FABRICANTE_SEQUENCE.NEXTVAL, 1, 'fabricante01');
INSERT INTO FABRICANTE VALUES (FABRICANTE_SEQUENCE.NEXTVAL, 2, 'fabricante02');
INSERT INTO FABRICANTE VALUES (FABRICANTE_SEQUENCE.NEXTVAL, 3, 'fabricante03');

INSERT INTO AUTOMOVEL VALUES (AUTOMOVEL_SEQUENCE.NEXTVAL,'AAA1111',1,1,1,1);
INSERT INTO AUTOMOVEL VALUES (AUTOMOVEL_SEQUENCE.NEXTVAL,'BBB2222',2,2,2,2);
INSERT INTO AUTOMOVEL VALUES (AUTOMOVEL_SEQUENCE.NEXTVAL,'CCC3333',3,1,3,3);

SELECT * FROM AUTOMOVEL A WHERE A.ID_CATEGORIA = 1; 
