INSERT  INTO TRACAO VALUES (1,'combustão');
INSERT  INTO TRACAO VALUES (2,'elétrico');

INSERT  INTO CATEGORIA VALUES (1,'particular');
INSERT  INTO CATEGORIA VALUES (2,'aluguel');
INSERT  INTO CATEGORIA VALUES (3,'oficial');

INSERT  INTO MODELO VALUES (1,'modelo01');
INSERT  INTO MODELO VALUES (2,'modelo02');
INSERT  INTO MODELO VALUES (3,'modelo03');

INSERT INTO PAIS VALUES (1, 'pais01');
INSERT INTO PAIS VALUES (2, 'pais02');
INSERT INTO PAIS VALUES (3, 'pais03');

INSERT INTO FABRICANTE VALUES (1,'fabricante01', 1);
INSERT INTO FABRICANTE VALUES (2,'fabricante02', 2);
INSERT INTO FABRICANTE VALUES (3,'fabricante03', 3);

INSERT INTO AUTOMOVEL VALUES (1,'AAA1111',1,1,1,1);
INSERT INTO AUTOMOVEL VALUES (2,'BBB2222',2,2,2,2);
INSERT INTO AUTOMOVEL VALUES (3,'CCC3333',3,3,3,2);