DROP TABLE IF EXISTS IMAGEM;
DROP SEQUENCE IF EXISTS IMAGEM_SEQ;
DROP TABLE IF EXISTS IDIOMA;
DROP SEQUENCE IF EXISTS IDIOMA_SEQ;
DROP TABLE IF EXISTS ESTADO;
DROP SEQUENCE IF EXISTS ESTADO_SEQ;
DROP TABLE IF EXISTS CIDADE;
DROP SEQUENCE IF EXISTS CIDADE_SEQ;
DROP TABLE IF EXISTS ENDERECO;
DROP SEQUENCE IF EXISTS ENDERECO_SEQ;
DROP TABLE IF EXISTS TELEFONE;
DROP SEQUENCE IF EXISTS TELEFONE_SEQ;
DROP TABLE IF EXISTS COMPETENCIA;
DROP SEQUENCE IF EXISTS CONPETENCIA_SEQ;
DROP TABLE IF EXISTS PESSOA;
DROP SEQUENCE IF EXISTS PESSOA_SEQ;
DROP TABLE IF EXISTS AUTOR;
DROP SEQUENCE IF EXISTS AUTOR_SEQ;
DROP TABLE IF EXISTS PESSOA_COMPETENCIA;
DROP SEQUENCE IF EXISTS PESSOA_COMPETENCIA_SEQ;
DROP TABLE IF EXISTS PERFIL;
DROP SEQUENCE IF EXISTS PERFIL_SEQ;
DROP TABLE IF EXISTS USUARIO;
DROP SEQUENCE IF EXISTS USUARIO_SEQ;
DROP TABLE IF EXISTS FUNCIONALIDADE;
DROP SEQUENCE IF EXISTS FUNCIONALIDADE_SEQ;
DROP TABLE IF EXISTS ACESSO_LOG;
DROP SEQUENCE IF EXISTS ACESSO_LOG_SEQ;
DROP TABLE IF EXISTS AUDIO_LIVRO_LEDOR;
DROP SEQUENCE IF EXISTS AUDIO_LIVRO_LEDOR_SEQ;
DROP TABLE IF EXISTS LIVRO_AUTOR;
DROP SEQUENCE IF EXISTS LIVRO_AUTOR_SEQ;
DROP TABLE IF EXISTS AULA;
DROP SEQUENCE IF EXISTS AULA_SEQ;
DROP TABLE IF EXISTS AULA_LEDOR;
DROP SEQUENCE IF EXISTS AULA_LEDOR_SEQ;
DROP TABLE IF EXISTS ASSUNTO;
DROP SEQUENCE IF EXISTS ASSUNTO_SEQ;
DROP TABLE IF EXISTS AUDIO_LIVRO;
DROP SEQUENCE IF EXISTS AUDIO_LIVRO_SEQ;
DROP TABLE IF EXISTS ACESSO_AUDIO_LIVRO;
DROP SEQUENCE IF EXISTS ACESSO_AUDIO_LIVRO_SEQ;
DROP TABLE IF EXISTS LIVRO;
DROP SEQUENCE IF EXISTS LIVRO_SEQ;
DROP TABLE IF EXISTS NOTICIA;
DROP SEQUENCE IF EXISTS NOTICIA_SEQ;

CREATE SEQUENCE IMAGEM_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IDIOMA_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ESTADO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE CIDADE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ENDERECO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TELEFONE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE CONPETENCIA_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PESSOA_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE AUTOR_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PESSOA_COMPETENCIA_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PERFIL_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE USUARIO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FUNCIONALIDADE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ACESSO_LOG_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE AULA_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE AULA_LEDOR_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE AUDIO_LIVRO_LEDOR_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LIVRO_AUTOR_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ASSUNTO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE AUDIO_LIVRO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ACESSO_AUDIO_LIVRO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LIVRO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE NOTICIA_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE IMAGEM(
	ID BIGINT NOT NULL DEFAULT IMAGEM_SEQ.NEXTVAL,
	NOME VARCHAR(50),
	URL VARCHAR(50),
	CONSTRAINT PK_IMAGEM PRIMARY KEY(ID)
);

CREATE TABLE IDIOMA(
	ID BIGINT NOT NULL DEFAULT IDIOMA_SEQ.NEXTVAL,
	NOME VARCHAR(50),
	CONSTRAINT PK_IDIOMA PRIMARY KEY(ID)
);

CREATE TABLE ESTADO(
  ID BIGINT NOT NULL DEFAULT ESTADO_SEQ.NEXTVAL,
  NOME VARCHAR(50),
  UF VARCHAR (5),
  CONSTRAINT PK_ESTADO PRIMARY KEY(ID)
);



CREATE TABLE CIDADE(
  ID BIGINT NOT NULL DEFAULT CIDADE_SEQ.NEXTVAL,
  NOME VARCHAR(50),
  ID_ESTADO BIGINT NOT NULL,
  CONSTRAINT PK_CIDADE PRIMARY KEY(ID),
  CONSTRAINT FK_CIDADE_ESTADO FOREIGN KEY(ID_ESTADO) REFERENCES ESTADO(ID)
);

CREATE TABLE ENDERECO(
  ID BIGINT NOT NULL DEFAULT ENDERECO_SEQ.NEXTVAL,
  ID_CIDADE BIGINT NOT NULL,
  BAIRRO VARCHAR(50),
  COMPLEMENTO VARCHAR(50),
  CEP INT(8),
  CONSTRAINT PK_ENDERECO PRIMARY KEY(ID),
  CONSTRAINT FK_ENDERECO_CIDADE FOREIGN KEY(ID_CIDADE) REFERENCES CIDADE(ID)
);

CREATE TABLE TELEFONE(
  ID BIGINT NOT NULL DEFAULT TELEFONE_SEQ.NEXTVAL,
  TIPO VARCHAR(1),
  NUMERO BIGINT(14),
  CONSTRAINT PK_TELEFONE PRIMARY KEY(ID)
);

CREATE TABLE COMPETENCIA(
  ID BIGINT NOT NULL DEFAULT CONPETENCIA_SEQ.NEXTVAL,
  NOME VARCHAR(50),
  DESCRICAO VARCHAR(50),
  CONSTRAINT PK_COMPETENCIA PRIMARY KEY(ID)
);

CREATE TABLE PESSOA(
  ID BIGINT NOT NULL DEFAULT PESSOA_SEQ.NEXTVAL,
  ID_ENDERECO BIGINT NOT NULL,
  ID_TELEFONE BIGINT NOT NULL,
  ID_RESPONSAVEL BIGINT NOT NULL,
  SEXO VARCHAR(1),
  NOME VARCHAR(50),
  CPF INT (11),
  RG INT (9),
  DATA_NASCIMENTO DATE NOT NULL,
  CONSTRAINT PK_PESSOA PRIMARY KEY(ID),
  CONSTRAINT FK_PESSOA_ENDERECO FOREIGN KEY(ID_ENDERECO) REFERENCES ENDERECO(ID),
  CONSTRAINT FK_PESSOA_PESSOA FOREIGN KEY(ID_RESPONSAVEL) REFERENCES PESSOA(ID),
  CONSTRAINT FK_PESSOA_TELEFONE FOREIGN KEY(ID_TELEFONE) REFERENCES TELEFONE(ID)
);

CREATE TABLE AUTOR(
  ID BIGINT NOT NULL DEFAULT AUTOR_SEQ.NEXTVAL,
  NOME VARCHAR(50) NOT NULL,
  DATA_NASCIMENTO DATE NOT NULL,
  CONSTRAINT PK_AUTOR PRIMARY KEY(ID)
);

CREATE TABLE PESSOA_COMPETENCIA(
  ID BIGINT NOT NULL DEFAULT PESSOA_COMPETENCIA_SEQ.NEXTVAL,
  ID_PESSOA BIGINT NOT NULL,
  ID_COMPETENCIA BIGINT NOT NULL,
  CONSTRAINT PK_PES_COMP PRIMARY KEY(ID),
  CONSTRAINT FK_PES_COMP_PESSOA FOREIGN KEY(ID_PESSOA) REFERENCES PESSOA(ID),
  CONSTRAINT FK_PES_COMP_COMPETENCIA FOREIGN KEY(ID_COMPETENCIA) REFERENCES COMPETENCIA(ID)
);

CREATE TABLE PERFIL(
  ID BIGINT NOT NULL DEFAULT PERFIL_SEQ.NEXTVAL,
  NOME VARCHAR(50) NOT NULL,
  DESCRICAO VARCHAR(50) NOT NULL,
  CONSTRAINT PK_PERFIL PRIMARY KEY(ID)
);

INSERT INTO  PERFIL VALUES ( PERFIL_SEQ.nextval,'Adiministrador','Perfil de Adiministrador do sistema');
INSERT INTO  PERFIL VALUES ( PERFIL_SEQ.nextval,'Aluno','Perfil de aluno');
INSERT INTO  PERFIL VALUES ( PERFIL_SEQ.nextval,'Ledor','Perfil de ledor');
INSERT INTO  PERFIL VALUES ( PERFIL_SEQ.nextval,'Professor','Perfil de professor');

CREATE TABLE USUARIO(
  ID BIGINT NOT NULL DEFAULT USUARIO_SEQ.NEXTVAL,
  ID_PESSOA BIGINT NOT NULL,
  ID_PERFIL BIGINT NOT NULL,
  LOGIN VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL,
  SENHA VARCHAR(50) NOT NULL,
  CONSTRAINT PK_USUARIO PRIMARY KEY(ID),
  CONSTRAINT FK_USUARIO_PESSOA FOREIGN KEY(ID_PESSOA) REFERENCES PESSOA(ID),
  CONSTRAINT FK_USUARIO_PERFIL FOREIGN KEY(ID_PERFIL) REFERENCES PERFIL(ID)
);

CREATE TABLE FUNCIONALIDADE(
  ID BIGINT NOT NULL DEFAULT FUNCIONALIDADE_SEQ.NEXTVAL,
  NOME VARCHAR(50) NOT NULL,
  DESCRICAO VARCHAR(50) NOT NULL,
  CONSTRAINT PK_FUNCIONALIDADE PRIMARY KEY(ID)
);

CREATE TABLE ACESSO_LOG(
  ID BIGINT NOT NULL DEFAULT ACESSO_LOG_SEQ.NEXTVAL,
  ID_FUNCIONALIDADE BIGINT NOT NULL,
  ID_USUARIO BIGINT NOT NULL,
  DESCRICAO VARCHAR(50) NOT NULL,
  DATA_ACESSO DATE NOT NULL,
  CONSTRAINT PK_ACESSO_LOG PRIMARY KEY(ID),
  CONSTRAINT FK_ACESSO_LOG_FUNCIONALIDADE FOREIGN KEY(ID_FUNCIONALIDADE) REFERENCES FUNCIONALIDADE(ID),
  CONSTRAINT FK_ACESSO_LOG_USUARIO FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID)
);

CREATE TABLE ASSUNTO(
  ID BIGINT NOT NULL DEFAULT ASSUNTO_SEQ.NEXTVAL,
  NOME VARCHAR(50) NOT NULL,
  DESCRICAO VARCHAR(50) NOT NULL,
  CONSTRAINT PK_ASSUNTO PRIMARY KEY(ID)
);

CREATE TABLE AULA(
  ID BIGINT NOT NULL DEFAULT AULA_SEQ.NEXTVAL,
  ID_ASSUNTO BIGINT NOT NULL,
  DATA_HORARIO_AULA DATE NOT NULL,
  DESCRICAO VARCHAR(50) NOT NULL,
  CONSTRAINT PK_AULA PRIMARY KEY(ID),
  CONSTRAINT FK_AULA_ASSUNTO FOREIGN KEY(ID_ASSUNTO) REFERENCES ASSUNTO(ID)
);

CREATE TABLE AULA_LEDOR(
  ID BIGINT NOT NULL DEFAULT AULA_LEDOR_SEQ.NEXTVAL,
  ID_LEDOR BIGINT NOT NULL,
  ID_AULA BIGINT NOT NULL,
  CONSTRAINT PK_AULA_LEDOR PRIMARY KEY(ID),
  CONSTRAINT FK_AULA_LEDOR_LEDOR FOREIGN KEY(ID_LEDOR) REFERENCES USUARIO(ID),
  CONSTRAINT FK_AULA_LEDOR_AULA FOREIGN KEY(ID_AULA) REFERENCES AULA(ID)
);

CREATE TABLE LIVRO(
  ID BIGINT NOT NULL DEFAULT LIVRO_SEQ.NEXTVAL,
  ID_IDIOMA BIGINT NOT NULL,
  TITULO VARCHAR2(50)  NOT NULL,
  SINOPSE VARCHAR(50) NOT NULL,
  EDITORA VARCHAR(50) NOT NULL,
  CONSTRAINT PK_LIVRO PRIMARY KEY(ID),
  CONSTRAINT FK_LIVRO_IDIOMA FOREIGN KEY(ID_IDIOMA) REFERENCES IDIOMA(ID)
);

CREATE TABLE LIVRO_AUTOR(
  ID BIGINT NOT NULL DEFAULT LIVRO_AUTOR_SEQ.NEXTVAL,
  ID_LIVRO BIGINT NOT NULL,
  ID_AUTOR BIGINT NOT NULL,
  CONSTRAINT PK_LIVRO_AUTOR PRIMARY KEY(ID),
  CONSTRAINT FK_LIVRO_AUTOR_LIVRO FOREIGN KEY(ID_LIVRO) REFERENCES LIVRO(ID),
  CONSTRAINT FK_LIVRO_AUTOR_AUTOR FOREIGN KEY(ID_AUTOR) REFERENCES AUTOR(ID)
);

CREATE TABLE AUDIO_LIVRO(
  ID BIGINT NOT NULL DEFAULT AUDIO_LIVRO_SEQ.NEXTVAL,
  ID_LIVRO_REFERENCIA BIGINT,
  TITULO VARCHAR(50) NOT NULL,
  URL_AUDIO VARCHAR(50) NOT NULL,
  CONSTRAINT PK_AUDIO_LIV PRIMARY KEY(ID),
  CONSTRAINT FK_AUDIO_LIV_LIVRO FOREIGN KEY(ID_LIVRO_REFERENCIA) REFERENCES LIVRO(ID)
);

CREATE TABLE ACESSO_AUDIO_LIVRO(
  ID BIGINT NOT NULL DEFAULT ACESSO_AUDIO_LIVRO_SEQ.NEXTVAL,
  ID_AUDIO_LIVRO BIGINT NOT NULL,
  ID_USUARIO BIGINT NOT NULL,
  DATA_ACESSO DATE NOT NULL,
  POSICAO_AUDIO NUMBER(4) NOT NULL,
  CONSTRAINT FK_ACESSO_AU_AUDLIVRO FOREIGN KEY(ID_AUDIO_LIVRO) REFERENCES AUDIO_LIVRO(ID),
  CONSTRAINT FK_ACESSO_AU_USUARIO FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID)
);


CREATE TABLE AUDIO_LIVRO_LEDOR(
  ID BIGINT NOT NULL DEFAULT AUDIO_LIVRO_LEDOR_SEQ.NEXTVAL,
  ID_AUDIO_LIVRO BIGINT NOT NULL,
  ID_LEDOR BIGINT NOT NULL,
  CONSTRAINT PK_AUD_LIV_LEDOR PRIMARY KEY(ID),
  CONSTRAINT FK_AUD_LIV_LEDOR_LEDOR FOREIGN KEY(ID_LEDOR) REFERENCES USUARIO(ID),
  CONSTRAINT FK_AUD_LIV_LEDOR_AUD_LIV FOREIGN KEY(ID_AUDIO_LIVRO) REFERENCES AUDIO_LIVRO(ID)
);

CREATE TABLE NOTICIA(
  ID BIGINT NOT NULL DEFAULT NOTICIA_SEQ.NEXTVAL,
  ID_IMAGEM BIGINT NOT NULL,
  ID_USUARIO BIGINT NOT NULL,
  TITULO VARCHAR(50) NOT NULL,
  CORPO VARCHAR(255) NOT NULL,
  CONSTRAINT PK_NOTICIA PRIMARY KEY(ID),
  CONSTRAINT FK_NOTICIA_IMAGEM FOREIGN KEY(ID_IMAGEM) REFERENCES IMAGEM(ID),
  CONSTRAINT FK_NOTICIA_USUARIO FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID)
);
