DROP TABLE IF EXISTS LEITURAS;
DROP SEQUENCE IF EXISTS LEITURAS_SEQ;
DROP TABLE IF EXISTS LEITURAS_LEITOR;
DROP SEQUENCE IF EXISTS LEITURAS_LEITOR_SEQ;
DROP TABLE IF EXISTS LEITURAS_LEDOR;
DROP SEQUENCE IF EXISTS LEITURAS_LEDOR_SEQ;
DROP TABLE IF EXISTS LEITURAS_ASSUNTO;
DROP SEQUENCE IF EXISTS LEITURAS_ASSUNTO_SEQ;
DROP TABLE IF EXISTS LEITURAS_IDIOMA;
DROP SEQUENCE IF EXISTS LEITURAS_IDIOMA_SEQ;
DROP TABLE IF EXISTS LEITURAS_TEMPO;
DROP SEQUENCE IF EXISTS LEITURAS_TEMPO_SEQ;

CREATE SEQUENCE LEITURAS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LEITURAS_LEDOR_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LEITURAS_LEITOR_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LEITURAS_ASSUNTO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LEITURAS_TEMPO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LEITURAS_IDIOMA_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE LEITURAS_LEITOR(
  ID BIGINT NOT NULL DEFAULT LEITURAS_LEITOR_SEQ.NEXTVAL,
  SEXO VARCHAR(1),
  NOME VARCHAR(50),
  IDADE NUMBER (3),
  CONSTRAINT PK_LEITURAS_LEITOR PRIMARY KEY(ID)
);

CREATE TABLE LEITURAS_LEDOR(
    ID BIGINT NOT NULL DEFAULT LEITURAS_LEDOR_SEQ.NEXTVAL,
    SEXO VARCHAR(1),
    NOME VARCHAR(50),
    IDADE NUMBER (3),
    CONSTRAINT PK_LEITURAS_LEDOR PRIMARY KEY(ID)
);

CREATE TABLE LEITURAS_IDIOMA(
  ID BIGINT NOT NULL DEFAULT LEITURAS_IDIOMA_SEQ.NEXTVAL,
  NOME VARCHAR(50),
  CONSTRAINT PK_LEITURAS_IDIOMA PRIMARY KEY(ID)
);

CREATE TABLE LEITURAS_ASSUNTO(
  ID BIGINT NOT NULL DEFAULT LEITURAS_ASSUNTO_SEQ.NEXTVAL,
  DESCRICAO VARCHAR(50),
  CONSTRAINT PK_LEITURAS_ASSUNTO PRIMARY KEY(ID)
);

CREATE TABLE LEITURAS_TEMPO(
  ID BIGINT NOT NULL DEFAULT LEITURAS_TEMPO_SEQ.NEXTVAL,
  ANO NUMBER(4),
  MES NUMBER(12),
  DATA DATE,
  CONSTRAINT PK_LEITURAS_TEMPO PRIMARY KEY(ID)
);

CREATE TABLE LEITURAS(
  ID BIGINT NOT NULL DEFAULT LEITURAS_SEQ.NEXTVAL,
  ID_LEITOR BIGINT NOT NULL,
  ID_ASSUNTO BIGINT NOT NULL,
  ID_TEMPO BIGINT NOT NULL,
  ID_LEDOR BIGINT NOT NULL,
  ID_IDIOMA BIGINT NOT NULL,
  CONSTRAINT PK_LEITURAS PRIMARY KEY(ID),
  CONSTRAINT FK_LEITURAS_LEITOR FOREIGN KEY(ID_LEITOR) REFERENCES LEITURAS_LEITOR(ID),
  CONSTRAINT FK_LEITURAS_ASSUNTO FOREIGN KEY(ID_ASSUNTO) REFERENCES LEITURAS_ASSUNTO(ID),
  CONSTRAINT FK_LEITURAS_TEMPO FOREIGN KEY(ID_TEMPO) REFERENCES LEITURAS_TEMPO(ID),
  CONSTRAINT FK_LEITURAS_LEDOR FOREIGN KEY(ID_LEDOR) REFERENCES LEITURAS_LEDOR(ID),
  CONSTRAINT FK_LEITURAS_IDIOMA FOREIGN KEY(ID_IDIOMA) REFERENCES LEITURAS_IDIOMA(ID)
);