DROP TABLE IF EXISTS LEITURAS;
DROP SEQUENCE IF EXISTS LEITURAS_SEQ;
DROP TABLE IF EXISTS LEDOR_LEITOR;
DROP SEQUENCE IF EXISTS LEDOR_LEITOR_SEQ;
DROP TABLE IF EXISTS ASSUNTO;
DROP SEQUENCE IF EXISTS ASSUNTO_SEQ;
DROP TABLE IF EXISTS IDIOMA;
DROP SEQUENCE IF EXISTS IDIOMA_SEQ;
DROP TABLE IF EXISTS TEMPO;
DROP SEQUENCE IF EXISTS TEMPO_SEQ;

CREATE SEQUENCE LEITURAS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LEDOR_LEITOR_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ASSUNTO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TEMPO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IDIOMA_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE LEDOR_LEITOR(
  ID BIGINT NOT NULL DEFAULT LEDOR_LEITOR_SEQ.NEXTVAL,
  SEXO VARCHAR(1),
  NOME VARCHAR(50),
  IDADE NUMBER (3),
  CONSTRAINT PK_LEDOR_LEITOR PRIMARY KEY(ID)
);

CREATE TABLE IDIOMA(
  ID BIGINT NOT NULL DEFAULT IDIOMA_SEQ.NEXTVAL,
  NOME VARCHAR(50),
  CONSTRAINT PK_IDIOMA PRIMARY KEY(ID)
);

CREATE TABLE ASSUNTO(
  ID BIGINT NOT NULL DEFAULT ASSUNTO_SEQ.NEXTVAL,
  DESCRICAO VARCHAR(50),
  CONSTRAINT PK_ASSUNTO PRIMARY KEY(ID)
);

CREATE TABLE TEMPO(
  ID BIGINT NOT NULL DEFAULT TEMPO_SEQ.NEXTVAL,
  ANO NUMBER(4),
  MES NUMBER(12),
  DATA DATE,
  CONSTRAINT PK_TEMPO PRIMARY KEY(ID)
);

CREATE TABLE LEITURAS(
  ID BIGINT NOT NULL DEFAULT LEITURAS_SEQ.NEXTVAL,
  ID_LEITOR BIGINT NOT NULL,
  ID_ASSUNTO BIGINT NOT NULL,
  ID_TEMPO BIGINT NOT NULL,
  ID_LEDOR BIGINT NOT NULL,
  ID_IDIOMA BIGINT NOT NULL,
  CONSTRAINT PK_LEITURAS PRIMARY KEY(ID),
  CONSTRAINT FK_LEITURAS_LEITOR FOREIGN KEY(ID_LEITOR) REFERENCES LEDOR_LEITOR(ID),
  CONSTRAINT FK_LEITURAS_ASSUNTO FOREIGN KEY(ID_ASSUNTO) REFERENCES ASSUNTO(ID),
  CONSTRAINT FK_LEITURAS_TEMPO FOREIGN KEY(ID_TEMPO) REFERENCES TEMPO(ID),
  CONSTRAINT FK_LEITURAS_LEDOR FOREIGN KEY(ID_LEDOR) REFERENCES LEDOR_LEITOR(ID),
  CONSTRAINT FK_LEITURAS_IDIOMA FOREIGN KEY(ID_IDIOMA) REFERENCES IDIOMA(ID)
);